version: "3.4"

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      #PROXY: proxy:3128
    ports:
      - 19132:19132/udp
    volumes:
      - bds:/data
    stdin_open: true
    tty: true
  #proxy:
  #image: sameersbn/squid

volumes:
  bds: {}
